version: '3.8'

services:
  backend:
    image: vayunotics/backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    image: vayunotics/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 