services:
  - type: web
    name: vayunotics-backend
    env: python
    buildCommand: pip install -r requirements.prod.txt
    startCommand: uvicorn final:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173,https://*.vercel.app
      - key: MAVLINK_CONNECTION
        value: tcp:127.0.0.1:5760
      - key: MAVLINK_BAUD_RATE
        value: "57600"
      - key: MAX_RECONNECT_ATTEMPTS
        value: "5"
      - key: RECONNECT_DELAY
        value: "2" 